-- MySQL Script generated by MySQL Workbench
-- Thu Jul 20 09:42:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Restaurante
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Restaurante` ;

-- -----------------------------------------------------
-- Schema Restaurante
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Restaurante` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Restaurante` ;


DROP TABLE IF EXISTS `Restaurante`.`Usuario` ;
DROP TABLE IF EXISTS `Restaurante`.`Mesa` ;
DROP TABLE IF EXISTS `Restaurante`.`Horario` ;
DROP TABLE IF EXISTS `Restaurante`.`Reserva` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
